from . import employee_assets
from . import hr
from . import hr_employee_public
from . import hr_gratuity
from . import leave_salary
from . import hr_payroll
from . import wps
from . import hr_resignation
from . import hr_leave_type
from . import hr_forms
from . import loan_application
from . import approval_matrix
from  . import hr_employee_request